imports:
    - { resource: listeners.yml }
    - { resource: registry.yml }
    - { resource: routing.yml }
    - { resource: storage.yml }
    - { resource: serializer.yml }

parameters:
    innmind_rest.listener.paginator: Innmind\Rest\Server\Paginator

services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: [@container]

    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver

    property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    storages:
        class: Innmind\Rest\Server\Storages

    request_parser:
        class: Innmind\Rest\Server\Request\Parser
        arguments:
            - @serializer
            - @formats
            - @negotiator

    formats:
        class: Innmind\Rest\Server\Formats

    negotiator:
        class: Negotiation\Negotiator

    entity_builder:
        class: Innmind\Rest\Server\EntityBuilder
        arguments:
            - @property_accessor
            - @event_dispatcher

    resource_builder:
        class: Innmind\Rest\Server\ResourceBuilder
        arguments:
            - @property_accessor
            - @event_dispatcher

    controller:
        class: Innmind\Rest\Server\Controller\ResourceController
        arguments:
            - @storages

    resource_validator:
        class: Innmind\Rest\Server\Validator
        arguments:
            - @validator

    validator:
        class: Symfony\Component\Validator\Validator
        factory:
            - Symfony\Component\Validator\Validation
            - createValidator

    paginator:
        class: %innmind_rest.listener.paginator%

    logger:
        class: Psr\Log\NullLogger
