services:
    request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack

    router:
        class: Symfony\Component\Routing\Router
        arguments: ['@route_loader', '.']

    route_loader:
        class: Innmind\Rest\Server\Routing\RouteLoader
        arguments:
            - '@event_dispatcher'
            - '@registry'
            - '@route_factory'

    route_factory:
        class: Innmind\Rest\Server\Routing\RouteFactory
