services:
    serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - []
            - []

    serializer.normalizer.resource:
        class: Innmind\Rest\Server\Serializer\Normalizer\ResourceNormalizer
        arguments:
            - @resource_builder
        tags:
            - { name: serializer.normalizer }

    serializer.encoder.json:
        class: Innmind\Rest\Server\Serializer\Encoder\JsonEncoder
        tags:
            - { name: serializer.encoder }
            - { name: format, format: json, mime: application/json, priority: 10 }

    serializer.encoder.form:
        class: Innmind\Rest\Server\Serializer\Encoder\FormEncoder
        tags:
            - { name: serializer.encoder }
            - { name: format, format: form, mime: application/x-www-form-urlencoded }
