services:
    storages:
        class: Innmind\Rest\Server\Storages

    storage.abstract.neo4j:
        class: Innmind\Rest\Server\Storage\Neo4jStorage
        abstract: true
        arguments:
            - ~
            - @event_dispatcher
            - @entity_builder
            - @resource_builder

    storage.abstract.doctrine:
        class: Innmind\Rest\Server\Storage\DoctrineStorage
        abstract: true
        arguments:
            - ~
            - @event_dispatcher
            - @entity_builder
            - @resource_builder
